updated keras definitions and wrapper script

diff --git a/keras/keras b/keras/keras
--- a/keras/keras
+++ b/keras/keras
@@ -4,14 +4,15 @@
 #U keras \- simple wrapper around a keras singularity container
 #U .SH SYNOPSIS
 #U .B keras
-#U command [options]
+#U [-B bindpath] command [command options]
 #U .SH DESCRIPTION
 #U .B keras
 #U is a convenience wrapper around a singularity container
 #U with keras and tensorflow-gpu. Note that it will only
 #U work on machines with CUDA installed (i.e. GPU nodes).
 #U [options] are passed on to the command. Note that, only
-#U the tensorflow backend is available.
+#U the tensorflow backend is available. -B is a bindpath
+#U string passed to singularity
 #U .SH COMMANDS
 #U .IP help 12
 #U display this help message
@@ -21,6 +22,8 @@
 #U Start a jupyter notebook.
 #U .IP python 12
 #U Used for running batch python scripts
+#U .IP shell 12
+#U get a bash shell inside the container
 #U .SH EXAMPLES
 #U .B keras
 #U ipython
@@ -42,9 +45,23 @@ function usage() {
         | less -e
 }
 
-keras_img="${PWD}/NIH-HPC-keras_demo-master.img"
+keras_img="${PWD}/keras-py2.simg"
 keras_backend="tensorflow"
 cmd="help"
+
+while getopts ":B:" opt; do
+    case $opt in
+        B)
+            export SINGULARITY_BINDPATH="$OPTARG"
+            ;;
+        \?)
+            echo "Invalid option: -$OPTARG" >&2
+            usage
+            exit 1
+            ;;
+    esac
+done
+shift $((OPTIND-1))
 
 while true; do
     case "$1" in
@@ -63,6 +80,11 @@ while true; do
             shift
             break
             ;;
+        shell)
+            cmd="shell"
+            shift
+            break
+            ;;
         *)
             usage
             exit 1
@@ -70,7 +92,6 @@ while true; do
     esac
 done
 
-export SINGULARITY_BINDPATH="/gpfs,/gs2,/gs3,/gs4,/gs5,/gs6,/gs7,/gs8,/spin1,/data,/scratch,/fdb,/lscratch"
 export KERAS_BACKEND="$keras_backend"
 
 case "$cmd" in
@@ -82,6 +103,9 @@ case "$cmd" in
         ;;
     notebook)
         singularity exec --nv "${keras_img}" jupyter notebook --no-browser
+        ;;
+    shell)
+        singularity exec --nv "${keras_img}" bash
         ;;
     help)
         usage
